name: control_gastos
description: Control de gastos personales
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.0
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.4
  fl_chart: ^0.70.0
  vibration: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true